### ISSUE TITLE
PRD Paymentech Job - Create Settlement Batch - Failed

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#110]
**Describe the bug**

**Instance Name**
Instance:  PPQS1I

**Responsibility Name**
Responsibility:   Funds Capture Process Manager

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Log file shows...

+---------------------------------------------------------------------------+
Payments: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

IBY_FC_CREATE_SETTLE_BATCHES: Create Settlement Batches
+---------------------------------------------------------------------------+

Current system time is 21-SEP-2021 13:14:28

+---------------------------------------------------------------------------+

CP main executing runProgram for oracle.apps.iby.scheduler.SchedInitiator
instr_type: CREDITCARD
prog_name: IBY_FC_CREATE_SETTLE_BATCHES
retry_flag: N
batch_name: 
Task Parameter: key: P_PAYMENT_SYSTEM_ID, value: 10022
Task Parameter: key: P_FC_CC_PROFILE_ID_SENTRY, value: X
Task Parameter: key: P_INTERNAL_PAYEE_ID, value: 025771
Task Parameter: key: P_PAYMENT_CHANNEL_CODE, value: CREDIT_CARD
Task Parameter: key: P_INSTRUMENT_TYPE, value: CREDITCARD
Task Parameter: key: P_CONC_PROGRAM_NAME, value: IBY_FC_CREATE_SETTLE_BATCHES
Task Parameter: key: P_CURRENCY_CODE, value: USD
Task Parameter: key: P_PAYMENT_SYSTEM_ACCOUNT_ID, value: 1
Task Parameter: key: P_RETRY_FLAG, value: N
Task Parameter: key: P_FC_CC_PROFILE_ID, value: 2

Processing BATCH CLOSE operations ..

After create extract, extract is not null.
Logging upto first 1MB of generated extract below:
==================

As info level logging is not enabled , hence not printing the extract

==================
Enter applyFormat Timestamp: Tue Sep 21 13:14:34 EDT 2021
Before emplateHelper.processTemplate Timestamp: Tue Sep 21 13:14:34 EDT 2021
After emplateHelper.processTemplate Timestamp: Tue Sep 21 13:14:35 EDT 2021
End ApplyFormat Timestamp: Tue Sep 21 13:14:35 EDT 2021
java.lang.ClassNotFoundException: oracle.apps.iby.bep.proc.paymentech.net.PTKSecureFTPPutFunction
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:356)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at oracle.apps.iby.engine.CodePoint.getImplementation(CodePoint.java:96)
	at oracle.apps.iby.engine.CodePoint.invokeJava(CodePoint.java:211)
	at oracle.apps.iby.engine.CodePoint.invoke(CodePoint.java:199)
	at oracle.apps.iby.engine.TransmitConfig.transmit(TransmitConfig.java:216)
	at oracle.apps.iby.payment.proc.BatchCCPayment.getBatchResp(BatchCCPayment.java:1279)
	at oracle.apps.iby.payment.proc.BatchCCPayment.closeBatch(BatchCCPayment.java:1039)
	at oracle.apps.iby.scheduler.SchedBatchClose.schedPmt(SchedBatchClose.java:438)
	at oracle.apps.iby.scheduler.Scheduler.doProcess(Scheduler.java:307)
	at oracle.apps.iby.scheduler.Scheduler.init(Scheduler.java:406)
	at oracle.apps.iby.scheduler.SchedInitiator.runProgram(SchedInitiator.java:215)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

Exception occured during formatting
oracle.apps.iby.exception.PSException: Error java.lang.ClassNotFoundException when loading class oracle.apps.iby.bep.proc.paymentech.net.PTKSecureFTPPutFunction .
	at oracle.apps.iby.util.bpsUtil.raiseException(bpsUtil.java:130)
	at oracle.apps.iby.engine.CodePoint.getImplementation(CodePoint.java:101)
	at oracle.apps.iby.engine.CodePoint.invokeJava(CodePoint.java:211)
	at oracle.apps.iby.engine.CodePoint.invoke(CodePoint.java:199)
	at oracle.apps.iby.engine.TransmitConfig.transmit(TransmitConfig.java:216)
	at oracle.apps.iby.payment.proc.BatchCCPayment.getBatchResp(BatchCCPayment.java:1279)
	at oracle.apps.iby.payment.proc.BatchCCPayment.closeBatch(BatchCCPayment.java:1039)
	at oracle.apps.iby.scheduler.SchedBatchClose.schedPmt(SchedBatchClose.java:438)
	at oracle.apps.iby.scheduler.Scheduler.doProcess(Scheduler.java:307)
	at oracle.apps.iby.scheduler.Scheduler.init(Scheduler.java:406)
	at oracle.apps.iby.scheduler.SchedInitiator.runProgram(SchedInitiator.java:215)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

Aborting request..
java.sql.SQLException: SQL string is not Query
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1464)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3769)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3823)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1671)
	at oracle.apps.iby.scheduler.SchedType.revertMBatchStatus(SchedType.java:566)
	at oracle.apps.iby.payment.proc.BatchCCPayment.closeBatch(BatchCCPayment.java:1064)
	at oracle.apps.iby.scheduler.SchedBatchClose.schedPmt(SchedBatchClose.java:438)
	at oracle.apps.iby.scheduler.Scheduler.doProcess(Scheduler.java:307)
	at oracle.apps.iby.scheduler.Scheduler.init(Scheduler.java:406)
	at oracle.apps.iby.scheduler.SchedInitiator.runProgram(SchedInitiator.java:215)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

oracle.apps.iby.exception.PSException: Error: an error occured during formatting API call to XML Publisher.
	at oracle.apps.iby.payment.proc.BatchCCPayment.closeBatch(BatchCCPayment.java:1055)
	at oracle.apps.iby.scheduler.SchedBatchClose.schedPmt(SchedBatchClose.java:438)
	at oracle.apps.iby.scheduler.Scheduler.doProcess(Scheduler.java:307)
	at oracle.apps.iby.scheduler.Scheduler.init(Scheduler.java:406)
	at oracle.apps.iby.scheduler.SchedInitiator.runProgram(SchedInitiator.java:215)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

exception occured for  : 2 Error: an error occured during formatting API call to XML Publisher.

The Stack Trace is -
oracle.apps.iby.exception.PSException: Error: an error occured during formatting API call to XML Publisher.
	at oracle.apps.iby.payment.proc.BatchCCPayment.closeBatch(BatchCCPayment.java:1055)
	at oracle.apps.iby.scheduler.SchedBatchClose.schedPmt(SchedBatchClose.java:438)
	at oracle.apps.iby.scheduler.Scheduler.doProcess(Scheduler.java:307)
	at oracle.apps.iby.scheduler.Scheduler.init(Scheduler.java:406)
	at oracle.apps.iby.scheduler.SchedInitiator.runProgram(SchedInitiator.java:215)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)


Finished processing BATCH CLOSE
CP main completed runProgram for oracle.apps.iby.scheduler.SchedInitiator
+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
Enter:TIMESTAMP:: IBY_EXTRACTGEN_PVT.Create_Extract:: 21-SEP-21 01.14.31.414311000 PM -04:00
Enter:TIMESTAMP::Extract(4 params) ::21-SEP-21 01.14.31.426915000 PM -04:00
Exit:TIMESTAMP::Extract(4 params) ::21-SEP-21 01.14.34.974324000 PM -04:00
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+


+---------------------------------------------------------------------------+
No completion options were requested.

Output file size: 
0
Deleting empty output file.

+---------------------------------------------------------------------------+
Concurrent request completed
Current system time is 21-SEP-2021 13:14:35

+---------------------------------------------------------------------------+

**Comment by hamiltonmark** [comment]
Here is log from Generating XML Templates on Sunday...


[101 XML_Publisher_Template_Re_Gene_190921.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7205106/101.XML_Publisher_Template_Re_Gene_190921.txt)

**Comment by vinaytalasila** [comment]
Mark,

I am looking into this issue and keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Mark,

I have compared the log file that you attached with that programs log file in INT 12.210 instance. In the log file that you attached, I see that PTKSecureFTPPutFunction.class is missing. I have requested DBA team to verify that file in the Production instance. I will keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Amit,

Ref: https://github.com/Fujitsu-America/Fujitsu-Repository/issues/92

As discussed in today's status meeting, could you please apply the Patch **19554624:R12**.IBY.C in the Production instance tonight. **Please let SBS team how much downtime is required for this activity so that we can get the approval from them.**

Thanks
Vinay

**Comment by SomuSundaramM** [comment]
Hi Mark,

We have applied the patch 19554624:R12.IBY.C in Prod, missing class files are present now. Please test the issue and confirm.

![image](https://user-images.githubusercontent.com/85238833/134465193-5bc4d4a9-86c2-433b-b451-1bbfead33529.png)

Thanks,
Som

**Comment by hamiltonmark** [comment]
Thanks Som
Millice has run Create Settlement Batches in Prod.
This job creates an XML file and transmits to Paymentech.
It completed successfully.
There is one additional step to run to Fetch the transactions back from Paymentech to EBS.
She will run that next.
I will give update when it is verified.
Thanks
Mark

![image](https://user-images.githubusercontent.com/85197361/134501620-9c24afb5-250b-4162-991e-d660df736932.png)

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your update.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Update...In today's status meeting Mark has confirmed that Paymentech to EBS is working good and has confirmed to 'Close' this issue.

Thanks
Vinay
