### ISSUE TITLE
PRD Fetch Settlement Batch Clearing - Failing - /ppqs1i/applmgr/CUSTOM/xbol/12.0.0/paymentech/Query/09270586.out.done (No such file or directory)

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#123]
**Describe the bug**

**Instance Name**
Instance:  PPQS1I

**Responsibility Name**
Responsibility:  Funds Capture Process Manager

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Cash Person submits - Fetch Settlement Batch Clearing - Result is error... Below is log...

+---------------------------------------------------------------------------+
Payments: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

IBY_FC_FETCH_BATCH_CLEARING: Fetch Settlement Batch Clearing
+---------------------------------------------------------------------------+

Current system time is 27-SEP-2021 12:17:50

+---------------------------------------------------------------------------+

CP main executing runProgram for oracle.apps.iby.scheduler.SchedInitiator
instr_type: null
prog_name: IBY_FC_FETCH_BATCH_CLEARING
retry_flag: null
batch_name: null
Task Parameter: key: P_CONC_PROGRAM_NAME, value: IBY_FC_FETCH_BATCH_CLEARING
Task Parameter: key: P_INTERNAL_PAYEE_ID, value: 025771
Task Parameter: key: P_PAYMENT_SYSTEM_ID, value: 10022
Task Parameter: key: P_PAYMENT_SYSTEM_ACCOUNT_ID, value: 1

Processing BATCH QUERY operations ..

attempting online batch query for (payee id=025771,bathcid id=2445_1)
java.io.FileNotFoundException: /ppqs1i/applmgr/CUSTOM/xbol/12.0.0/paymentech/Query/09270586.out.done (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
	at oracle.apps.xdo.delivery.ssh2.sftp.SftpClient.get(Unknown Source)
	at oracle.apps.xdo.delivery.ssh2.sftp.SftpClient.get(Unknown Source)
	at oracle.apps.xdo.delivery.ssh2.sftp.SFTPUtil.get(Unknown Source)
	at oracle.apps.iby.bep.proc.net.SecureFTPUtils.retrieveFileBits(SecureFTPUtils.java:201)
	at oracle.apps.iby.bep.proc.paymentech.net.BatchFileFinder.getBatchFile(BatchFileFinder.java:237)
	at oracle.apps.iby.bep.proc.paymentech.net.GetSecureBatchACKFunction.transmit(GetSecureBatchACKFunction.java:248)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at oracle.apps.iby.engine.CodePoint.invokeJava(CodePoint.java:250)
	at oracle.apps.iby.engine.CodePoint.invoke(CodePoint.java:199)
	at oracle.apps.iby.engine.TransmitConfig.transmit(TransmitConfig.java:256)
	at oracle.apps.iby.payment.proc.BatchCCPayment.getBatchResp(BatchCCPayment.java:1277)
	at oracle.apps.iby.payment.proc.BatchCCPayment.queryBatch(BatchCCPayment.java:1232)
	at oracle.apps.iby.scheduler.SchedBatchQuery.schedPmt(SchedBatchQuery.java:212)
	at oracle.apps.iby.scheduler.Scheduler.doProcess(Scheduler.java:307)
	at oracle.apps.iby.scheduler.Scheduler.init(Scheduler.java:406)
	at oracle.apps.iby.scheduler.SchedInitiator.runProgram(SchedInitiator.java:215)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at oracle.apps.iby.engine.CodePoint.invokeJava(CodePoint.java:250)
	at oracle.apps.iby.engine.CodePoint.invoke(CodePoint.java:199)
	at oracle.apps.iby.engine.TransmitConfig.transmit(TransmitConfig.java:256)
	at oracle.apps.iby.payment.proc.BatchCCPayment.getBatchResp(BatchCCPayment.java:1277)
	at oracle.apps.iby.payment.proc.BatchCCPayment.queryBatch(BatchCCPayment.java:1232)
	at oracle.apps.iby.scheduler.SchedBatchQuery.schedPmt(SchedBatchQuery.java:212)
	at oracle.apps.iby.scheduler.Scheduler.doProcess(Scheduler.java:307)
	at oracle.apps.iby.scheduler.Scheduler.init(Scheduler.java:406)
	at oracle.apps.iby.scheduler.SchedInitiator.runProgram(SchedInitiator.java:215)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)
Caused by: oracle.apps.iby.exception.PSException: Communication error. The payment system, the processor, or iPayment electronic commerce servlet is not available/accessible. Please make sure you have the correct system set up and resubmit the request at a later time.
	at oracle.apps.iby.bep.proc.paymentech.net.GetSecureBatchACKFunction.transmit(GetSecureBatchACKFunction.java:288)
	... 14 more

Either the Ack file has not been generated for the current batch or no match has been found.

Finished processing BATCH QUERY
Task Parameter: key: P_CONC_PROGRAM_NAME, value: IBY_FC_FETCH_BATCH_CLEARING
Task Parameter: key: P_INTERNAL_PAYEE_ID, value: 025771
Task Parameter: key: P_PAYMENT_SYSTEM_ID, value: 10022
Task Parameter: key: P_PAYMENT_SYSTEM_ACCOUNT_ID, value: 1

Processing PDC BATCH QUERY operations ..


Finished processing PDC BATCH QUERY
Task Parameter: key: P_CONC_PROGRAM_NAME, value: IBY_FC_FETCH_BATCH_CLEARING
Task Parameter: key: P_INTERNAL_PAYEE_ID, value: 025771
Task Parameter: key: P_PAYMENT_SYSTEM_ID, value: 10022
Task Parameter: key: P_PAYMENT_SYSTEM_ACCOUNT_ID, value: 1

Processing EFT BATCH QUERY operations ..


Finished processing EFT BATCH QUERY
CP main completed runProgram for oracle.apps.iby.scheduler.SchedInitiator
+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+


+---------------------------------------------------------------------------+

**Comment by hamiltonmark** [comment]
Expected Folder does not exist....


login as: mhamil
mhamil@psbsashebsap1.oci.snapbs.com's password:
Last login: Thu Sep 23 14:00:28 2021 from 172.22.216.7
[mhamil@psbsashebsap1 ~]$ sudo su apppqs1i
[sudo] password for mhamil:

  E-Business Suite Environment Information
  ----------------------------------------
  RUN File System           : /ppqs1i/12.2/PROD/fs2/EBSapps/appl
  PATCH File System         : /ppqs1i/12.2/PROD/fs1/EBSapps/appl
  Non-Editioned File System : /ppqs1i/12.2/PROD/fs_ne


  DB Host: psbsashebsdb1.oci.snapbs.com  Service/SID: PPQS1I


  Sourcing the RUN File System ...

[apppqs1i@psbsashebsap1 mhamil]$ cd /ppqs1i/applmgr/CUSTOM/xbol/12.0.0/paymentech/Query
bash: cd: /ppqs1i/applmgr/CUSTOM/xbol/12.0.0/paymentech/Query: No such file or directory
[apppqs1i@psbsashebsap1 mhamil]$ cd /ppqs1i
[apppqs1i@psbsashebsap1 ppqs1i]$ cd applmgr
bash: cd: applmgr: No such file or directory
[apppqs1i@psbsashebsap1 ppqs1i]$ ls -ltr
total 7309904
-rw-r--r--  1 apppqs1i  dba         43541529 Nov 26  2012 12_20210917173523.bak
-rw-r--r--  1 apppqs1i  dba         43541529 Nov 26  2012 12_20210824091300.bak
drwxr-xr-x  3 apppqs1i  dba               18 Aug 23 11:13 12.2_17sep21
-rw-r--r--  1 tp_ppqs1i tp_ppqs1i 1191910547 Aug 27 23:52 3rdparty.tar.gz
-rw-r--r--  1 apppqs1i  dba       6080989140 Aug 28 01:35 apex.tar.gz
-rw-------  1 apppqs1i  dba        125334742 Aug 28 05:02 nohup.out
drwxrwx---  7 apppqs1i  dba              133 Aug 30 01:24 oraInventory_17sep21
drwxr-xr-x  3 apppqs1i  dba               18 Sep 17 13:25 12.2
drwxr-xr-x  8 apexords  apexords        4096 Sep 18 22:26 apex
drwxr-xr-x 12 tp_ppqs1i tp_ppqs1i       4096 Sep 19 20:57 3rdparty
drwxrwx---  7 apppqs1i  dba              133 Sep 22 06:52 oraInventory
drwxr-xr-x  7 apppqs1i  dba               70 Sep 27 06:06 applcsf
[apppqs1i@psbsashebsap1 ppqs1i]$

**Comment by hamiltonmark** [comment]
$XBOL_TOP/paymentch/Query  does not seem to be pointing to the correct folder in PROD.


[apppqs1i@psbsashebsap1 Query]$ hostname
psbsashebsap1.oci.snapbs.com
[apppqs1i@psbsashebsap1 Query]$ whoami
apppqs1i
[apppqs1i@psbsashebsap1 Query]$ pwd
/ppqs1i/12.2/PROD/fs2/EBSapps/appl/xbol/12.0.0/paymentech/Query
[apppqs1i@psbsashebsap1 Query]$

**Comment by vinaytalasila** [comment]
**@arsidhan / @SomuSundaramM:**  Can one of you look into this issue in the Production instance?

Thanks
Vinay

**Comment by hamiltonmark** [comment]
One of the Prod Setups for Paymentech - showing the expected folder...

![image](https://user-images.githubusercontent.com/85197361/134954242-264c41ea-0283-4a1b-b31f-b57d7eedd824.png)

**Comment by SomuSundaramM** [comment]
Hi Mark,

XBOL_TOP path is /ppqs1i/12.2/PROD/fs2/EBSapps/appl/xbol/12.0.0, but in this program it is pointing to older instance (12.1.3 path).

I got this profile values from paymentch profile settings, here we need to replace the $XBOL_TOP path. Can you please guide me steps to set this profile values.

/ppqs1i/applmgr/CUSTOM/xbol/12.0.0/paymentech/Query --> /ppqs1i/12.2/PROD/fs2/EBSapps/appl/xbol/12.0.0/paymentech/Query

/ppqs1i/applmgr/CUSTOM/xbol/12.0.0/paymentech/Batch -->
/ppqs1i/12.2/PROD/fs2/EBSapps/appl/xbol/12.0.0/paymentech/Batch


![image](https://user-images.githubusercontent.com/85238833/134954434-9f5fac97-8aed-4eaa-933d-cd0d902e0f22.png)

Thanks,
Som

**Comment by hamiltonmark** [comment]
Som
I will make the changes in PROD for these setups.
Will let you know when complete so you can re-run the script.
Give me 10 mins...
Thanks
Mark

**Comment by hamiltonmark** [comment]
Som
Prod Setup changes are done.
Can you please run the script and post results?
Thanks
Mark

**Comment by SomuSundaramM** [comment]
Hi Mark,

I took those values from old excel sheets, i dont have any scripts to check the values again. You can re-run the concurrent program to see that it resolves our issue.

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Ok - changes made in PROD
Here are the results.
We will try again.

![image](https://user-images.githubusercontent.com/85197361/134957694-665d8788-c6f8-4a8e-a6e3-1d0e5de01c51.png)

**Comment by hamiltonmark** [comment]
Thanks Som
That fixed the issue.

Our Cash Person just completed the iPayment Process for another batch of invoices (from Service Contracts) with credit cards.
1. Create Auto Receipts
2. Create Auto Remittances
3. Create Settlement Batches
4. Fetch Settlement Batches
5. Automatic Clearing for Receipts

All the receipts in this batch settled and cleared. There were no duplicate receipts.

**Comment by hamiltonmark** [comment]
Vinay
This ticket can be closed.
THanks
Mark

**Comment by SomuSundaramM** [comment]
Hi Mark,

Thank you for the confirmation.

Regards,
Som
