### ISSUE TITLE
INT 12.2.10 Uninvoiced Receipts Report - Post Processing Services failing ** SR 3-26519530311 : Uninvoiced Receipts Report failing after 12.1.3 to 12.2.10 Upgrade

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#91]
**Describe the bug**

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:   PBS US Payables Manager

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Submit Conc Job:   Uninvoiced Receipts Report
Log shows Post Processing is failing...


+---------------------------------------------------------------------------+
Bills of Material: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

CSTACREP: Uninvoiced Receipts Report
+---------------------------------------------------------------------------+

Current system time is 19-JUL-2021 11:54:17

+---------------------------------------------------------------------------+

[19-JUL-2021 11:54:17]: **Starts**
[19-JUL-2021 11:54:21]: **Ends**
+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+


+---------------------------------------------------------------------------+
Executing request completion options...

Output file size: 
15063

+--------- 1) POST-PROCESSING  ---------+
Beginning post-processing of request 35438951 on node ISBSASHEBSAP4 at 19-JUL-2021 11:54:21.
-- Publishing output

 
Post-processing of request 35438951 failed at 19-JUL-2021 11:54:22 with the error message:
One or more post-processing actions failed. Consult the OPP service log for details.
 
CONC-POST-PROCESSING RESULTS

-- PUBLISH: 
oracle.apps.fnd.cp.opp.PostProcessorException: oracle.apps.fnd.cp.opp.PostProcessorException: oracle.apps.xdo.XDOException
+---------------------------------------+


Finished executing request completion options.

+---------------------------------------------------------------------------+
Concurrent request completed
Current system time is 19-JUL-2021 11:54:22

+---------------------------------------------------------------------------+

**Comment by hamiltonmark** [comment]
[Sequence 197 and 198 - Concurrent Warning with Results Attached.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6842551/Sequence.197.and.198.-.Concurrent.Warning.with.Results.Attached.zip)

**Comment by hamiltonmark** [comment]
Manager Log from Concurrent Manager:  Output Post Processor 


[7/19/21 2:15:50 PM] [3382191:RT35439095] Executing post-processing actions for request 35439095.
[7/19/21 2:15:50 PM] [3382191:RT35439095] Starting XML Publisher post-processing action.
[7/19/21 2:15:50 PM] [3382191:RT35439095] 
Template code: CSTACREP
Template app:  BOM
Language:      en
Territory:     US
Output type:   RTF
[7/19/21 2:15:50 PM] [3382191:RT35439095] Output file was found but is zero sized - Deleted
[7/19/21 2:15:50 PM] [UNEXPECTED] [3382191:RT35439095] java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at oracle.apps.xdo.common.xml.XSLT10gR1.invokeProcessXSL(Unknown Source)
	at oracle.apps.xdo.common.xml.XSLT10gR1.transform(Unknown Source)
	at oracle.apps.xdo.common.xml.XSLT10gR1.transform(Unknown Source)
	at oracle.apps.xdo.common.xml.XSLTWrapper.transform(Unknown Source)
	at oracle.apps.xdo.template.fo.util.FOUtility.generateFO(Unknown Source)
	at oracle.apps.xdo.template.fo.util.FOUtility.generateFO(Unknown Source)
	at oracle.apps.xdo.template.FOProcessor.createFO(Unknown Source)
	at oracle.apps.xdo.template.FOProcessor.generate(Unknown Source)
	at oracle.apps.xdo.oa.schema.server.TemplateHelper.runProcessTemplate(TemplateHelper.java:5990)
	at oracle.apps.xdo.oa.schema.server.TemplateHelper.processTemplate(TemplateHelper.java:3481)
	at oracle.apps.xdo.oa.schema.server.TemplateHelper.processTemplate(TemplateHelper.java:3570)
	at oracle.apps.fnd.cp.opp.XMLPublisherProcessor.process(XMLPublisherProcessor.java:311)
	at oracle.apps.fnd.cp.opp.OPPRequestThread.run(OPPRequestThread.java:185)
Caused by: oracle.xdo.parser.v2.XPathException: Extension function error: Method not found 'xdo_format_number'
	at oracle.xdo.parser.v2.XSLStylesheet.flushErrors(XSLStylesheet.java:1534)
	at oracle.xdo.parser.v2.XSLStylesheet.execute(XSLStylesheet.java:521)
	at oracle.xdo.parser.v2.XSLStylesheet.execute(XSLStylesheet.java:489)
	at oracle.xdo.parser.v2.XSLProcessor.processXSL(XSLProcessor.java:271)
	at oracle.xdo.parser.v2.XSLProcessor.processXSL(XSLProcessor.java:155)
	at oracle.xdo.parser.v2.XSLProcessor.processXSL(XSLProcessor.java:192)
	... 16 more

[7/19/21 2:15:50 PM] [3382191:RT35439095] Completed post-processing actions for request 35439095.

**Comment by hamiltonmark** [comment]
MOS Hit shows the following...

[Uninvoiced Receipts Report Is Competing With A Warning - Meth.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6843138/Uninvoiced.Receipts.Report.Is.Competing.With.A.Warning.-.Meth.docx)

**Comment by vinaytalasila** [comment]
Mark,

We will look into this and keep you posted. 

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Amit / Somu,

Could you please check whether the post processing services are running in INT 12.2.10 instance.

Thanks
Vinay

**Comment by SomuSundaramM** [comment]
Hi Vinay,

Yes it is up and running in INT.

Thanks,
Somu

**Comment by vinaytalasila** [comment]
**@amitjori:** Could you please refer to the 'Uninvoiced Receipts Report Is Competing With A Warning - Meth.docx' and apply the solution in INT 12.2.10 instance tonight.

Thanks
Vinay

**Comment by amitjori** [comment]
Hi Mark,

Executed the solution given in note id 1996766.1 in INT 12.2.10 instance, can you please retest this issue and confirm?

![image](https://user-images.githubusercontent.com/85238919/126619401-4175081a-5891-4ba1-88eb-2e90cd8c72fe.png)

**Comment by hamiltonmark** [comment]
Amit
I re-tested... Unfortunately - same error.
I will enter an SR for this issue.
Below is both Log from Conc Request and Manager Log from Conc Mgr.
Thanks
Mark

+---------------------------------------------------------------------------+
Bills of Material: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

CSTACREP: Uninvoiced Receipts Report
+---------------------------------------------------------------------------+

Current system time is 22-JUL-2021 07:58:58

+---------------------------------------------------------------------------+

[22-JUL-2021 07:58:58]: **Starts**
[22-JUL-2021 07:59:05]: **Ends**
+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+


+---------------------------------------------------------------------------+
Executing request completion options...

Output file size: 
15063

+--------- 1) POST-PROCESSING  ---------+
Beginning post-processing of request 35443038 on node ISBSASHEBSAP4 at 22-JUL-2021 07:59:05.
-- Publishing output

 
Post-processing of request 35443038 failed at 22-JUL-2021 07:59:06 with the error message:
One or more post-processing actions failed. Consult the OPP service log for details.
 
CONC-POST-PROCESSING RESULTS

-- PUBLISH: 
oracle.apps.fnd.cp.opp.PostProcessorException: oracle.apps.fnd.cp.opp.PostProcessorException: oracle.apps.xdo.XDOException
+---------------------------------------+


Finished executing request completion options.



Template code: IEXSCEHR
Template app:  IEX
Language:      en
Territory:     00
Output type:   PDF
[7/22/21 6:07:55 AM] [3384691:RT35442918] XML Publisher post-processing action complete.
[7/22/21 6:07:55 AM] [3384691:RT35442918] Completed post-processing actions for request 35442918.
[7/22/21 7:59:05 AM] [OPPServiceThread0] Post-processing request 35443038.
[7/22/21 7:59:05 AM] [3384691:RT35443038] Executing post-processing actions for request 35443038.
[7/22/21 7:59:06 AM] [3384691:RT35443038] Starting XML Publisher post-processing action.
[7/22/21 7:59:06 AM] [3384691:RT35443038] 
Template code: CSTACREP
Template app:  BOM
Language:      en
Territory:     US
Output type:   RTF
[7/22/21 7:59:06 AM] [3384691:RT35443038] Output file was found but is zero sized - Deleted
[7/22/21 7:59:06 AM] [UNEXPECTED] [3384691:RT35443038] java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at oracle.apps.xdo.common.xml.XSLT10gR1.invokeProcessXSL(Unknown Source)
	at oracle.apps.xdo.common.xml.XSLT10gR1.transform(Unknown Source)
	at oracle.apps.xdo.common.xml.XSLT10gR1.transform(Unknown Source)
	at oracle.apps.xdo.common.xml.XSLTWrapper.transform(Unknown Source)
	at oracle.apps.xdo.template.fo.util.FOUtility.generateFO(Unknown Source)
	at oracle.apps.xdo.template.fo.util.FOUtility.generateFO(Unknown Source)
	at oracle.apps.xdo.template.FOProcessor.createFO(Unknown Source)
	at oracle.apps.xdo.template.FOProcessor.generate(Unknown Source)
	at oracle.apps.xdo.oa.schema.server.TemplateHelper.runProcessTemplate(TemplateHelper.java:5990)
	at oracle.apps.xdo.oa.schema.server.TemplateHelper.processTemplate(TemplateHelper.java:3481)
	at oracle.apps.xdo.oa.schema.server.TemplateHelper.processTemplate(TemplateHelper.java:3570)
	at oracle.apps.fnd.cp.opp.XMLPublisherProcessor.process(XMLPublisherProcessor.java:311)
	at oracle.apps.fnd.cp.opp.OPPRequestThread.run(OPPRequestThread.java:185)
Caused by: oracle.xdo.parser.v2.XPathException: Extension function error: Method not found 'xdo_format_number'
	at oracle.xdo.parser.v2.XSLStylesheet.flushErrors(XSLStylesheet.java:1534)
	at oracle.xdo.parser.v2.XSLStylesheet.execute(XSLStylesheet.java:521)
	at oracle.xdo.parser.v2.XSLStylesheet.execute(XSLStylesheet.java:489)
	at oracle.xdo.parser.v2.XSLProcessor.processXSL(XSLProcessor.java:271)
	at oracle.xdo.parser.v2.XSLProcessor.processXSL(XSLProcessor.java:155)
	at oracle.xdo.parser.v2.XSLProcessor.processXSL(XSLProcessor.java:192)
	... 17 more

[7/22/21 7:59:06 AM] [3384691:RT35443038] Completed post-processing actions for request 35443038.

**Comment by hamiltonmark** [comment]
Opened SR 3-26519530311 : Uninvoiced Receipts Report failing after 12.1.3 to 12.2.10 Upgrade

**Comment by hamiltonmark** [comment]
Quick response from SR Analyst...
Can you please execute in INT 12.2.10?
Thanks
Mark

--------------------UPDATE ACTION PLAN DETAILS BELOW---------------------
Owner
------------------------------------------------------
Mark


ACTION PLAN
-------------------------------------------------------


Go to XML Publisher Administration responsibility
Requests > Run
Chose name =XML Publisher Template Re-Generator
On Re-Generation Criteria parameter select value 'All'
Press on Submit button

**Comment by amitjori** [comment]
Hi Mark,

This has been done in INT 12.2.10 instance, please re-test.

Regards,
Amit

**Comment by hamiltonmark** [comment]
Thank you Amit... Success!

![image](https://user-images.githubusercontent.com/85197361/126644521-ad0f5cb9-fb8d-4758-99d3-548388ddb3b7.png)

**Comment by hamiltonmark** [comment]
Response from tester - Mark Pastor...

![image](https://user-images.githubusercontent.com/85197361/126664712-b2cff76b-9057-4255-99b2-f8f8626491a2.png)

**Comment by hamiltonmark** [comment]
Ticket can be closed.
